### PR TITLE
Feature development The Next Web Clone

### PR DESCRIPTION
**Pull request by Aduda-Boaz**
This PR is for The Next web clone project for Microverse practical learning. 
The clone project is developed by @ad9311  and @Aduda-Boaz, with -:

- HTML 
- CSS
- Git Workflows
The PR marks the completion of Milestone 2 of the HTML CSS Curriculum and ready for review.

### CODE REVIEW

**Review by MkrtichSargsyan — CHANGES_REQUESTED** [review]
## _Status:_ Changes Requested :recycle:

## Hello Guys

THIS IS VERY IMPRESSIVE WORK. YOU HAVE DONE A GOOD JOB :+1:

 However, there are some changes that you need to make in order to get your project approved


- [x] Each article has a title (hx tag), which is a link (a tag).  Kindly make your titles as a link
  
link

<br>

- [x] In the Latest news section there should be 4 articles per row for the Desktop size

# Original
  
original

  # Your's
  
ln


- [x] Titles of the categories should be as a links

categories_titles

<br>

- [x] Kindly remove all unused class names from the index.html


-   header_popular
-   popular_content
-   latest_deals


<hr>

## OPTIONAL

- [x] Add h1 tag To the page

  theoretically and logically wrong to have subheadlines ```<h2>``` without a main headline ```<h1>```,   but it won't have a negative effect.

- [x] you have ```margin-left: 20px``` in your articles for tablet and desctop versions
  it would be nice if you fix this

  mar

<be>

- [x] Text is overlapping, kindly fix this

  overlapping

<br>

## Please, make the REQUIRED changes and submit your request again! :grinning:
Good luck. 

> ps: . If you have any questions about my review or need help, you can message me on slack ( @mkrtichsargsyan )

**Comment by ad9311** [comment]
#### Greetings @MkrtichSargsyan 👋🏽 

The issues previously stated have been addressed as well as the optional ones. 
The following changes were made:
- All articles' 'hx' are links now.
- The news section now displays 4 rows in desktop mode.
- Fixed margin and padding issues.
- Added hover effect to links.
- Added one 'h1' tag to the page. Located in the first picture on the highlights section. 

We hope the changes are satisfactory.

**Review by DeliceLydia — APPROVED** [review]
# Status: Approved image

Congratulations @Aduda-Boaz and @ad9311 for your hard work this project speaks by itself that you took your time to design it and you implemented all changes requested by the previous TSE.

## Kudos once again feel free to merge and move on to the next project

All the best,

Lydia Ingabire

**Comment by Aduda-Boaz** [comment]
Thank you @DeliceLydia for your Approval message. This is more than a motivation to us to keep working hard. We are more than happy.

**Pull request merged**
